examples/stan-sub.go
stan.go
stan_test.go
sub.go

See [Current Go report card for master](https://goreportcard.com/report/github.com/nats-io/go-nats-streaming)

Fix go report card issues

---

stan.go
stan_test.go

Add a NatsConn method to the Conn interface which allows retrieving the
underlying NATS Conn. Addresses #67.

Expose NATS Conn

---

README.md

- Renamed MaxInFlight to MaxInflight (lowercase f) to match code.
- Adding missing double quote

Fix some typos in the README.

---

stan.go
stan_test.go

Add MaxPubAcksInFlight option

---

examples/stan-bench.go
stan.go
stan_test.go

The introduced option setter had a case that did not match the
option it is setting and the similar Subscription's option
MaxInflight
Related to PR #88

[CHANGED] MaxPubAcksInFlight to MaxPubAcksInflight

---

examples/stan-pub.go
examples/stan-sub.go
stan.go
stan_test.go

Also fixed the pub and sub example to use this option setter. They
would otherwise only be able to connect to localhost:4222.
Resolves #94

[ADDED] Option setter for the URL client connects to

---

README.md
stan_test.go

The support for Durable Queue Subscribers has been added to the
server in master branch. Add documentation in README and test
for durable queue subs.

Document and test for durable queue subscribers

---

stan.go

Saw one of these in ~~my dreams~~ a memory profile. For simple cases like "%s.%s" where both arguments are already passed as strings using the + operator avoids an allocation (at least most of the time. I think there is a limit based on the string size after which an allocation is needed) and some overhead from Sprintf itself.
Benchmark results:
```
name                old time/op    new time/op    delta
Publish-8             63.3µs ± 1%    60.3µs ± 1%   -4.69%          (p=0.008 n=5+5)
PublishAsync-8        3.03µs ± 2%    2.70µs ± 2%  -10.90%          (p=0.008 n=5+5)
Subscribe-8           2.00µs ± 2%    2.01µs ± 2%     ~             (p=0.452 n=5+5)
QueueSubscribe-8      2.45µs ± 1%    2.48µs ± 4%     ~             (p=0.310 n=5+5)
PublishSubscribe-8    4.72µs ± 3%    4.52µs ± 2%   -4.12% …
```

Avoid fmt.Sprintf for simple subjects

---

stan.go
stan_test.go

Currently it is possible to customize a raw NATS connection though if is not connected already then client panics when attempting to connect to the Streaming server.
```go
package main
import (
"fmt"
"github.com/nats-io/go-nats-streaming"
"github.com/nats-io/nats"
)
func main() {
opts := nats.DefaultOptions
nc := nats.Conn{Opts: opts}
_, err := stan.Connect("test-cluster", "client-123", stan.NatsConn(&nc))
fmt.Printf("ERROR: %s\n", err)
// ERROR: stan: invalid connection
}
```
Before:
```
STDERR: 
panic: assignment to entry in nil map
goroutine 1 [running]:
panic(0x25be60, 0xc42000d010)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/nats-io/nats.(*Conn).subscribe(0xc420095680, 0xc420010f20, 0x1d, 0x0, 0x0, 0xc42000d000, 0x0, 0x0, 0x0, 0x0) …
```

Bail if custom NATS conn is disconnected when connecting to Streaming

---

sub.go

In some environments, when the NATS streaming server is under heavy load, two seconds may not be long enough for subscriber requests.  It seems reasonable that the connect timeout could be used in requests made by the subscriber API.  
An alternative is to offer a new subscriber option, although I don't see much value in that - we would typically recommend the same value as that used for connection requests.

Use the connect timeout for subscriber requests

---

pb/protocol.pb.go
pb/protocol.proto
stan.go
stan_test.go
sub.go

Resolves #114
Will require https://github.com/nats-io/nats-streaming-server/issues/182
to be implemented.

[ADDED] Subscription.Close() allows closing durable

---

stan_test.go

Since the server is no longer failing when those APIs are used
with values out-of-range, the tests needed to be updated.

Updated tests related to StartAtTimeDelta and StartAtSequence

---

examples/stan-bench.go

Stan-bench can now use remote servers specified on the command line.
Removed the text regarding providing a comma separated list of multiple servers. I'm not sure if this is even an option with the way the rest of the test is setup.

updated stan-bench.go to use the -s url specified on the command line.

---

.travis.yml
stan_test.go

Removed TestRedeliveryHonorMaxInflight since server now always
send messages during redelivery.
Furthermore, this was more a server test than client test.

Remove test and update Travis

---

stan_test.go

Use a standalone NATS Server for this test so that we check
that requests timeout due to NATS Streaming server being shutdown
and don't get broken pipe from NATS Server not running.

Fix TestTimeoutOnRequests test

---

pb/protocol.pb.go
pb/protocol.proto
sub.go

This is related to PR #115 and server side [PR 203](https://github.com/nats-io/nats-streaming-server/pull/203).
I noticed that we could have used `UnsubscribeRequest` since content
of that one and `SubscriptionCloseRequest` were same for relevant fields.
Also, the server was actually implemented with `UnsubscribeRequest`
and works fine. What matters is the subject the protocol is sent to.

Remove SubscriptionCloseRequest protocol

---

stan_test.go
sub.go

I wanted to get some subscription metrics available in nats that were not available in streaming such as # of pending messages, # of delivered messages, etc. I think allowing these metrics to be exposed increases programmer usability to build better systems around nats streaming.
The tests were pulled from sub_test.go

Expose some nats subscription methods in streaming

---

stan.go
stan_test.go

Related: https://github.com/nats-io/go-nats-streaming/issues/33
Currently the connection name for a STAN server viewed from the nats connection page are always empty. Making it difficult to debug connections.
This PR propagates STAN clientID down to the NATS connection, and should fix this issue.

Propagate STAN clientID to Nats Conn for better debugging

---

stan.go
stan_test.go

It is possible that the client timeout at the same time that it
receives the pubAck from the server. It is acceptable to have
the client report a failure because it timed-out, even though
the ack has just been received, but it is not correct to invoke
the AckHandler twice for the same guid.
Also, the issue would cause serious problems for synchronous
Publish() calls. See issue report for details.
Resolves #130

[FIXED] Possible duplicate processing of a PubAck

---

stan.go

There is also a change in the server to return a more specific
error should a client provide an invalid client ID. It will make
it clear for the user why the connect fails.
(Server PR: https://github.com/nats-io/nats-streaming-server/pull/306)
Resolves #133

[DOC] The requirements for client ID [ci skip]

---

stan_test.go

Removed dependency of `go-nats/test` before we switch test to be unexported.

removed dependency on go-nats/test

---

README.md

I have updated "Subscription Start (i.e. Replay) Options" section.
There are was not specified module for Options: `StartWithLastReceived`, `DeliverAllAvailable`,  `StartAtSequence`, `StartAtTime`, `StartAtTimeDelta`

[UPDATED] Subscription Start Options section in Readme 

---

README.md
examples/stan-bench/main.go
examples/stan-sub/main.go
stan.go
stan_test.go

This will help the client library detect and report that
the connection to the Streaming server is permanently lost.
This also allows the server to detect that a client has
been replaced by another one with the same client ID.
Imagine a client being disconnected from the streaming
server. At the same time, another application that can
communicate with the streaming server creates a connection
with the same client ID. The server detects the duplicate
ID, tries to contact the original client, but can't,
assume that it has terminated and replaces it.
When the original client resumes communication with the
server, it should now fail because the connection is
no longer "valid". For that, the client PINGs contain
a connection ID that uniquely identify any connection (NUID).
When the server gets …

[ADDED] PINGs from client to server

---

examples/stan-bench/main.go

The cluster ID option was missing from usage
Resolves #198

[FIXED] stan-bench usage [ci skip]

---

README.md

Explain that one needs to create a NATS Connection and configure
it as desired, then pass it to the stan.Connect() with the
stan.NatsConn() option function.
Resolves #173

[ADDED] Doc about advanced configuration of a connection [ci skip]

---

.travis.yml
stan.go
stan_test.go

When the NATS connection is passed to the Connect() call and
that call fails (for any reason), then some internal NATS subscriptions
may not be unsubscribed.
Resolves #226

[FIXED] NATS Subscriptions leak on failed Connect()

---

stan.go

[IMPROVED] behavior of Conn.Close() when NATS connection is provided

---

stan.go
stan_test.go

Setting internal subscriptions and subMap to nil on subscription
close seem to eliminate the inuse_space report from go tool pprof
Resolves #251

[FIXED] Reduce in-use memory space on connection close

---

README.md

Doing "go get github.com/nats-io/stan.go" reports an error about
"no such file or directory" although things are downloaded ok.
However, doing "go get github.com/nats-io/stan.go/" (with the
trailing "/") works fine.

Update the "go get" instruction to avoid error report [ci skip]

---

stan.go

DEPRECATED: Use GetDefaultOptions() instead.
DefaultOptions is not safe for use by multiple clients.
For details see https://github.com/nats-io/nats.go/issues/308.
DefaultOptions are the NATS Streaming client's default options
Signed-off-by: anxinyf <anxinyf@gmail.com>

Generate default config for each request.

---

examples/stan-bench/README.md
examples/stan-bench/filestore.conf
examples/stan-bench/main.go
examples/stan-pub/main.go
examples/stan-sub/main.go

Signed-off-by: Derek Collison <derek@nats.io>

Updated for NATS 2.0, added README for benchmarks

---

examples/stan-sub/main.go

In PR #274, some changes were made which caused stan-sub to be
a queue group by default, but then there is no way to make it
a plain subscription. Reverting this change.

Fixed examples/stan-sub

---

README.md

Similar to the one for the NATS Go client.

Add note on workaround for Go modules go get

---

stan.go

When a client calls stan.Connect() with a cluster ID that is
different that the server's cluster ID, the request will timeout.
This is expected since the server does not receive the connect
request at all, so the client times out waiting for the reply.
We are adding a hint in the error message which may help some users:
`stan: connect request timeout (possibly wrong cluster ID?)`
Resolves #285

[IMPROVED] Added wrong cluster ID hint in connect timeout error

---

.travis.yml
scripts/cov.sh
stan.go
stan_test.go
sub.go

Obverved with a subscription with very high MaxInflight (100,000)
and server on different machine that subscription would miss
messages (gap in new messages sequence) which was tracked down
to the internal susbcription dropping messages when reaching
the 64K default pending limit.

[FIXED] Set internal NATS subscriptions limits to "unlimited"

---

stan.go
stan_test.go
sub.go

- Move all ping related fields into own pingInfo struct.
- Use connection closed boolean to check/set closed state instead
of setting nc to nil. That makes sc.nc immutable and not nil
and so code using that doesn't have to capture/check.
- Add a pubAckCloseChan that is closed during connection close
to prevent publish call from being possibly blocked.
Regarding last point, we have tests and I tried to add a new one
but it would not catch the issue unless I would add a sleep in
publishAsync() after check of connection close and before sending
to pubAckChan.
The race is that if the connection is fully closed between these
two lines then if there are enough go routines trying to send to
the pubAckChan or MaxPubAcksInflight is low, the channel could be
full which would block the …

Cleanup some code

---

stan.go
stan_test.go

We can't invoke the ack handler from the connection close code
since there would be a possible deadlock if user code is calling
any connection method.
This is based out of #297 but without the change on how pub acks
are timed-out (still use timers). So this PR has only tests fixes
and the fix for failing pub acks on connection close.

[FIXED] Fail of publish ack on connection close

---

stan.go

Nothing in the exposed API takes an `Options`, only `Option`.
(Unless you count the `Option` type needing to have `Options` in its
signature).
`GetDefaultOptions` can't be withdrawn without an API break, so add text
explaining.

Clarify GetDefaultOptions is not for clients

---

README.md
stan.go
stan_test.go

Almost no change compared to v0.6.0, but updated dependencies and
want to do a NATS Streaming server release, which then will reference
this new release.

Prepare for release v0.7.0

---

.travis.yml
stan.go

The current defaults were too small and would cause a client to
mark the connection as lost after 15 seconds or so. This means
that a server restart or leadership change may lead to the client
dropping the connection.
Made the change so that the overall time the client keeps the
connection valid is as long as the server default ping settings.
Of course, user that use Pings() option are not affected. This
is only changing the default values.
Also, in the event that the server no longer has the client, the
client will detect that at the first ping interval, which is
5 seconds (the interval has not changed).

[CHANGED] Default Ping settings

---

pb/protocol.pb.go
stan.go

Fix the Unmarshal possible overflow and also do not make the library
panic on Unmarshal errors.
We don't have a proper way to return those errors since they happen
in callbacks. For now, just printing. May add a callback error later.

[FIXED] No panic on protobuf Unmarshal errors

---

stan_test.go
sub.go

If an application gets a timeout on a Subscribe() call, it does not
know if the server is actually going to process the request. The request
could have been just processed but the client timed-out before getting
the response back, or there is a bit of a backlog of requests in the
server and the request will be processed after the request times out
in the client.
If that happens, and if the application maintains its connection, then
it is possible that the server processes the subscription and keep that
subscription alive, although the application does not have an handle
on this subscription (the Subscribe() call has failed).
On timeout, the library will now send a request to close the subscription.
However, the protocol normally requires the AckInbox which is assigned by
the server and …

[FIXED] Subscribe timeout should send a close request

---

.travis.yml
README.md
stan.go

Release 0.8.3

---

stan.go
stan_test.go

This allows users that don't want to create their own NATS connection
to configured as desired, to pass the NATS options they would use
to create the NATS connection.
With that, the streaming connection will create and own the NATS
connection but will be configured based on the provided NATS options,
except for some options that are overridden by the library.
Resolve #354

[ADDED] NatsOptions to configure the NATS connection on stan.Connect()

---

stan.go
stan_test.go
sub.go

If a connection is closed, or a subscription is closed or unsubscribed,
and an error occurs at the protocol level, for instance getting a
timeout or the NATS connection is currently disconnected, etc..
the Close()/Unsubscribe() calls would return an error but the user
would not be able to invoke them again, in the sense that these
calls would bail out early because those objects were already marked
as closed.
This was problematic because if an application closes a connection for
instance but gets a timeout, then there is no way for the application
to really try to tell the server that the connection should be closed.
(same for subscription).
This PR let the user call Close()/Unsubscribe() if the library failed
to get a response from the server (likely timeout or NATS communication
issue). …

[FIXED] Conn and Subscription Close()/Unubscribe() could not be retried

---

stan.go
stan_test.go

In PR #360, we changed the default behavior of connection Close()
in that if the library failed to sent the close protocol or received
its response, the Close() could be retried. In order to do that,
the underlying NATS connection would not be closed.
This has side-effects in that the NATS connection would be left
opened or possibly reconnect when an user would have previously
called Close(), not check error, and expect NATS connection to
be closed.
The introduction of this option allow the default behavior to
remain the same, and users that do want to be able to call Close()
again on a failed call will need to set this option when creating
the connection.

[ADDED] AllowCloseRetry option

---

stan_test.go
sub.go

- modified subscribe fn to unregister sub from subMap when subscribe fails
- mofiifed TestSubTimeout test
fixes #365

[FIXED] Prevent memory leak on subscription failure
