examples/stan-bench.go

- Minor output fix
- Add ID parameter to run multiple instances simultaneously.

Updates to the benchmark

---

README.md

Users cutting and pasting code snippets were getting confused by errors.

Fix code snippet errors

---

README.md

[REMOVED] Removed limitations that have been addressed in subsequent versions of the server or api.
[ADDED] Note describing that streaming server subscriptions do not support wildcards.
@kozlovic @ColinSullivan1 @lparis

[ci skip] Updates to Readme.md

---

examples/stan-sub.go

To be consistent with other examples programs, changed code to not
use the "." import.

[CHANGED] Import of stan-sub.go

---

stan_test.go

- [REMOVED] TestBasicPubSubFlowControl since this test was not
proving anything and we have TestManualAck and TestMaxPubAcksInflight
to demonstrate flow control for both sub and pub respectively.
- [UPDATED] TestMaxChannels so that we start the server with a small
number of channels.
Resolves #37

[UPDATED] Tests

---

.travis.yml

Update Go 1.6.3 to 1.6.4 in Travis

---

.travis.yml
stan.go
stan_test.go
sub.go

Removed tests that belong in the server and increased code coverage.

Removed server tests and improved code coverage

---

stan_test.go

Changes due to https://github.com/nats-io/nats-streaming-server/pull/264

Updated calls to RunServerWithOpts based on server changes

---

examples/stan-bench.go

Fixes issue #140.
@nats-io/core

Fix stan-bench usage string

---

.travis.yml
stan.go

This tool combines staticcheck, gosimple and unused.
Fixed reports from unused.

Added megacheck

---

examples/stan-bench.go

The tool was originally keeping track of the start time on the
start of the subscription. This would report wrong messages rate
if the publisher was started later.
The start time is now taken when receiving the first message.

[FIXED] Benchmark tool now starts timer for sub on first message

---

examples/stan-bench/main.go

Similar to stan-pub and stan-sub, the flag `-c` or `-cluster` now
allows you to specify the cluster name. It was previously hard-coded
to `test-cluster` (the default NATS Streaming cluster name)

[ADDED] Ability to specify cluster name in stan-bench tool

---

examples/stan-bench/main.go

[FIXED] Benchmark tool: fail on PublishAsync error report

---

GOVERNANCE.md
MAINTAINERS.md
OWNERS

Add GOVERNANCE.md
Update and Rename OWNERS to MAINTAINERS.md
[ci skip]

Add Governance/Maintainers

---

.travis.yml

Update Go version in Travis

---

stan_test.go
sub.go

[FIXED] Race condition on subscribe and connection close

---

README.md

I was always searching for it. Not it will be there like the go-nats repo.

Adding godoc badge

---

stan.go

Specify that one can pass a comma separated list of urls.
Resolves #223

[UPDATED] Doc of NatsURL [ci skip]

---

stan.go
stan_test.go

Prepare for 0.4.2 release

---

stan.go

We were calling c.Close() inside Connect() for any failure
condition. The problem is that Close() is trying to send a
close request, which does not make sense (and will fail with
invalid subject internally since closeRequests subject is "").
So for any failure before processing the ConnectResponse will
now call a function that does proper cleanup without trying to
send the close request protocol.
After getting a ConnectionResponse OK we *must* call Close()
since we need to let the server know that we are actually
closing (no connection is returned to the user, so user can't
Close() explicitly).

Skip code that would try to send CloseRequest on failed connect

---

stan.go
sub.go

[FIXED] Adding some missing documentation on exported symbols

---

stan.go

[IMPROVED] Added proper godoc for the Conn interface's method set

---

stan.go

Release 0.4.4

---

.travis.yml
README.md
examples/stan-bench/main.go
examples/stan-pub/main.go
examples/stan-sub/main.go
stan.go
stan_test.go
sub.go

Changes due to repo rename

---

stan.go

Release 0.4.5

---

.gitignore
stan.go

deprecate PingIterval

---

go.mod
go.sum
stan_test.go

Add go.mod and fix nats-server imports for v2

---

stan.go

Release v0.5.0

---

stan.go

Hello.
Seems like there should be _less than_ condition and not _less or equal than_.
Please, correct me if I am missing it.

Fix MaxOut pings check

---

stan.go
sub.go

[FIXED] Documentation missing thread-safety note

---

README.md
stan.go

Release 0.5.2

---

.travis.yml
README.md
stan.go

Release v0.6.0

---

pb/protocol.proto

[DOC] MsgProto.Timestamp precision

---

stan.go

Release v0.8.0

---

pb/protocol.pb.go

[FIXED] More fixes to protobuf Unmarshal

---

stan.go

Release v0.8.1

---

stan.go

Release v0.8.2

---

README.md
stan.go

Release v0.9.0

---

README.md
stan.go

Release v0.10.3

---

README.md
stan.go

Release v0.10.4
